n = -5:5;
x = zeros(1, length(n));
offset = 5 + 1;
x(offset - 2) = 1;
x(offset - 1) = -2;
x (offset) = 3;
x(offset + 1) = 6;
n_y1 = -n;
[n_y1, idx] = gsort(n_y1, 'g', 'i');
y1 = x(idx);
clf();
subplot(2, 1, 1);
plot2d3(n,x);
xlabel("n");
ylabel("x(n)");
title("x(n)");
subplot(2, 1, 2);
plot2d3(n_y1,y1);
xlabel("n");
ylabel("y1(n)");
title("y1(n) = x(-n)");
