n = -5:5;
x = zeros(1, length(n));
offset = 5 + 1;
x(offset - 2) = 1;
x(offset - 1) = -2;
x (offset) = 3;
x(offset + 1) = 6;
n_y2 = n-3;
[n_y2, idx] = gsort(n_y2, 'g', 'i');
y2 = x(idx);
clf();
subplot(2, 1, 1);
plot2d3(n,x);
xlabel("n");
ylabel("x(n)");
title("x(n)");
subplot(2, 1, 2);
plot2d3(n_y2,y2);
xlabel("n");
ylabel("y2(n)");
title("y2(n) = x(n+3)");
