n = -5:5;
x = zeros(1, length(n));
offset = 5 + 1;
x(offset - 1) = 1;
x(offset) = 3;
x(offset + 1) = -2;
n_xneg = -n;
[n_xneg, idx] = gsort(n_xneg, 'g', 'i');
x_neg = x(idx);
x_e = (x + x_neg) / 2;
x_o   = (x - x_neg) / 2;
clf();
subplot(3,1,1);
plot2d3(n, x);
title("Tin hieu x(n)");
xlabel("n"); 
ylabel("x(n)");
subplot(3,1,2);
plot2d3(n, x_e);
title("Tin hieu x_e(n)");
xlabel("n"); 
ylabel("x_e(n)");
subplot(3,1,3);
plot2d3(n, x_o);
title("Tin hieu x_o(n)");
xlabel("n"); 
ylabel("x_o(n)");
