n = -5:5;
x = zeros(1, length(n));
offset = 5 + 1;
x(offset - 2) = 1;
x(offset - 1) = -2;
x (offset) = 3;
x(offset + 1) = 6;
n_y3 = n + 2;
n_y3 = -n_y3;
[n_y3, idx] = gsort(n_y3, 'g', 'i');
y3 = 2*x(idx);
clf();
subplot(2, 1, 1);
plot2d3(n,x);
xlabel("n");
ylabel("x(n)");
title("x(n)");
subplot(2, 1, 2);
plot2d3(n_y3,y3);
xlabel("n");
ylabel("y3(n)");
title("y3(n) = 2x(-n-2)");
